# Generated by Django 4.0.6 on 2022-08-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
