# Generated by Django 4.0.6 on 2022-08-21 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_notes_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendship',
            old_name='my_friend',
            new_name='friend',
        ),
        migrations.RenameField(
            model_name='friendship',
            old_name='me',
            new_name='user',
        ),
        migrations.AddField(
            model_name='friendship',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Friend_request',
        ),
    ]
